apiVersion: apps/v1
kind: Deployment
metadata:
  name: faster-whisper-server-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faster-whisper-server-k8s
  template:
    metadata:
      labels:
        app: faster-whisper-server-k8s
    spec:
      containers:
      - name: faster-whisper-server-k8s
        image: miyurud/miyuru-image:cpu
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "34000m"
            memory: "12Gi"
          limits:
            cpu: "36000m"
            memory: "14Gi"
