apiVersion: apps/v1
kind: Deployment
metadata:
  name: faster-whisper-gpu
spec:
  replicas: 4
  selector:
    matchLabels:
      app: faster-whisper-server-k8s
      type: gpu
  template:
    metadata:
      labels:
        app: faster-whisper-server-k8s
        type: gpu
    spec:
      dnsPolicy: Default
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      nodeSelector:
        role: single-target
      containers:
      - name: faster-whisper-gpu
        image: fedirz/faster-whisper-server:latest-cuda
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/mig-1g.10gb: 1
            cpu: "2000m"
            memory: "8Gi"
